課題13の提出
kenfmb/Portfolio pull request #10
Opened 2024-09-18 17:12 UTC by kenfmb

課題13の提出です。
ご確認よろしくお願いします。

2024-09-19 08:41 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2024-09-19 08:41 UTC, MasatoshiMizumoto commented on .ansible/roles/nginx/vars/main.yml
EOFの警告が出ていますので解消をお願いします！

2024-09-19 08:41 UTC, MasatoshiMizumoto commented on .ansible/roles/nginx/tests/test.yml
EOFの警告が出ていますので解消をお願いします！

2024-09-19 08:41 UTC, MasatoshiMizumoto commented on .ansible/roles/nginx/meta/main.yml
EOFの警告が出ていますので解消をお願いします！

2024-09-19 08:41 UTC, MasatoshiMizumoto commented on .ansible/roles/nginx/handlers/main.yml
EOFの警告が出ていますので解消をお願いします！

2024-09-19 08:41 UTC, MasatoshiMizumoto commented on .ansible/roles/nginx/defaults/main.yml
EOFの警告が出ていますので解消をお願いします！

2024-09-19 08:41 UTC, MasatoshiMizumoto commented on .ansible/roles/nginx/.travis.yml
EOFの警告が出ていますので解消をお願いします！

2024-09-19 09:28 UTC, kenfmb commented on .ansible/roles/nginx/vars/main.yml
修正しました。
ご確認よろしくお願いします。

2024-09-19 09:28 UTC, kenfmb commented on .ansible/roles/nginx/tests/test.yml
修正しました。
ご確認よろしくお願いします。

2024-09-19 09:28 UTC, kenfmb commented on .ansible/roles/nginx/meta/main.yml
修正しました。
ご確認よろしくお願いします。

2024-09-19 09:28 UTC, kenfmb commented on .ansible/roles/nginx/handlers/main.yml
修正しました。
ご確認よろしくお願いします。

2024-09-19 09:29 UTC, kenfmb commented on .ansible/roles/nginx/defaults/main.yml
修正しました。
ご確認よろしくお願いします。

2024-09-19 09:29 UTC, kenfmb commented on .ansible/roles/nginx/.travis.yml
修正しました。
ご確認よろしくお願いします。

2024-09-19 10:41 UTC, MasatoshiMizumoto approved these changes
LGTMです！

2024-09-20 13:50 UTC, kenfmb commented
ありがとうございます。

2024-09-20 13:50 UTC, merged